name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  args: ^2.4.0
  yaml: ^3.1.1
  dart_console: ^1.1.2
  interact: ^2.2.0
  dartz: ^0.10.1
  file: ^6.1.4
  json2yaml: ^3.0.1
  mason: ^0.1.0-dev.49
  mason_logger: ^0.2.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
