name: presto_cli
description: A sample command-line application.
version: 1.0.13
publish_to: https://gitlab.com/Ahmed-Omar-Prestoeat/presto_cli
homepage: https://gitlab.com/Ahmed-Omar-Prestoeat/presto_cli

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  args: ^2.4.0
  dart_console: ^1.1.2
  interact: ^2.2.0
  dartz: ^0.10.1
  file: ^6.1.4
  json2yaml: ^3.0.1
  mason: ^0.1.0-dev.49
  mason_logger: ^0.2.5
  image: ^4.0.15
  archive: ^3.3.7
  analyzer: ^5.10.0
  yaml: ^3.1.2
  http: ^0.13.6
  mockito: ^5.4.0
  mocktail: ^0.3.0
  async: ^2.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  build_version: ^2.1.1

executables:
  presto: presto_cli